SELECT * FROM TAB;

SELECT 12*8-4/2+1
FROM DUAL;

SELECT SYSDATE, USER
FROM DUAL;


CREATE TABLE EMPLOYEE
(
	SSN      NUMBER(7) PRIMARY KEY,
	ENAME    VARCHAR2(50)  not null,
	ADDRESS  VARCHAR2(70),
	GENDER   CHAR(1) CHECK (GENDER IN('F','M','f','m')),
	SALARY   NUMBER(8,2),
	DNO      NUMBER(2),
	CONSTRAINT EMPLOYEE_SALARY_CK CHECK(SALARY BETWEEN 2000 AND 50000)   
)

DESCRIBE EMPLOYEE;

ALTER TABLE EMPLOYEE ADD MILITARY_STAUS VARCHAR2(20);

DESC EMPLOYEE;

ALTER TABLE EMPLOYEE MODIFY MILITARY_STAUS VARCHAR2(30);


ALTER TABLE EMPLOYEE DROP COLUMN MILITARY_STAUS;


CREATE TABLE DEPARTMENT
(	
	DNO          NUMBER(2) ,
	DAME         VARCHAR2(30) UNIQUE,
	PHONE        CHAR(4),
	MANAGER_SSN  NUMBER(7),
	CONSTRAINT DEPARTMENT_DNO_PK PRIMARY KEY(DNO),
	CONSTRAINT DEPARTMENT_MANAGER_SSN_FK FOREIGN KEY(MANAGER_SSN) REFERENCES EMPLOYEE(SSN)
	ON DELETE RESTRICT
)
	
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_DN_FK FOREIGN KEY(DNO) REFERENCES DEPARTMENT(DNO) 
ON DELETE CASCADE;


SELECT * 
FROM   USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMPLOYEE';


INSERT INTO DEPARTMENT
VALUES(10,'SALES','2345',NULL);

INSERT INTO DEPARTMENT
VALUES(20,'ACCOUNTING','2346',NULL);

INSERT INTO DEPARTMENT(MANAGER_SSN, DAME,DNO)
VALUES(NULL,'IT',30);


DESC EMPLOYEE;

INSERT INTO EMPLOYEE (SSN, ENAME,SALARY,dno )
VALUES(100,'Ali',1500,30)

INSERT INTO EMPLOYEE (SSN, ENAME,SALARY,dno )
VALUES(100,'Ali',2500,70)

INSERT INTO EMPLOYEE (SSN, ENAME,SALARY,dno )
VALUES(100,'Ali',2500,10)

INSERT INTO EMPLOYEE (SSN, ENAME,SALARY,dno )
VALUES(101,'Said',3000,10)

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;

DELETE
FROM  DEPARTMENT
WHERE DNO =30;

UPDATE DEPARTMENT
SET    MANAGER_SSN=100
WHERE  DNO=20;

SELECT * FROM DEPARTMENT;


DELETE
FROM EMPLOYEE
WHERE SSN=100;


TRUNCATE TABLE EMPLOYEE;

DELETE
FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;
SELECT * FROM TAB;

SELECT *
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
ORDER BY SALARY DESC;


SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 101
ORDER BY SALARY DESC;


SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 5000
ORDER BY SALARY DESC;


SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10 , 30, 70)
ORDER BY SALARY DESC;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%M%' 
ORDER BY SALARY DESC;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%M%' OR FIRST_NAME LIKE '%m%'
ORDER BY SALARY DESC;


SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME) LIKE '%M%' 
ORDER BY SALARY DESC;


SELECT EMPLOYEE_ID, UPPER(FIRST_NAME), LOWER(FIRST_NAME),INITCAP(FIRST_NAME)
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME) LIKE '%M%' 
ORDER BY FIRST_NAME DESC;

SELECT EMPLOYEE_ID, UPPER(FIRST_NAME), LOWER(FIRST_NAME),INITCAP(FIRST_NAME), FIRST_NAME
FROM EMPLOYEES
WHERE LOWER(FIRST_NAME) LIKE '%n_' 
ORDER BY FIRST_NAME ASC;

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME, SALARY
FROM EMPLOYEES INNER JOIN DEPARTMENTS
USING (DEPARTMENT_ID)
ORDER BY FIRST_NAME DESC;

SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME, SALARY
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
WHERE SALARY BETWEEN 2000 AND 5000
ORDER BY FIRST_NAME DESC;


SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_NAME, SALARY
FROM EMPLOYEES E , DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND   FIRST_NAME LIKE '_a%'
ORDER BY FIRST_NAME DESC;