/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barc;
import java.awt.Image;
import java.sql.*;
import javax.swing.*;
import java.io.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
/**
 *
 * @author Moataz
 */
public class display extends javax.swing.JFrame {

    String s;
    public display() {
        initComponents();
        for (int i = 1995; i < 2050; i++) {
            YearCombo.addItem(i);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        facTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        YearCombo = new javax.swing.JComboBox();
        imgLabel = new javax.swing.JLabel();
        AttachBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DeptTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        classCombo = new javax.swing.JComboBox();
        Back = new javax.swing.JButton();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Class:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 300, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Barcode ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Faculty :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(facTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 300, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Year :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 300, 30));

        YearCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Year", "" }));
        YearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearComboActionPerformed(evt);
            }
        });
        getContentPane().add(YearCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 30));
        getContentPane().add(imgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 230, 170));

        AttachBtn.setBackground(new java.awt.Color(153, 51, 0));
        AttachBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AttachBtn.setText("Attach Image");
        AttachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AttachBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        getContentPane().add(DeptTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 300, 30));

        addBtn.setText("Save");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 70, 40));

        classCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        classCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classComboActionPerformed(evt);
            }
        });
        getContentPane().add(classCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 80, 30));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 80, 30));
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
            try {
            
            String url="jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8" ;
            String username="root";
            String password="";

            Connection con = DriverManager.getConnection(url,username,password);
            PreparedStatement ps 
            = con.prepareStatement
            ("insert into student(studentID,name,class,year,department,faculty,image) values(?,?,?,?,?,?,?)");

            /*
            Statement stmt = con.createStatement();
            String Query= " INSERT INTO student(studentID,name,class,year,department,faculty,image ) "
            + " VALUES ('"+idTxt.getText()+"','"+nameTxt.getText()+"' "
            + ",'"+classCombo.getSelectedItem()+"','"+YearCombo.getSelectedItem()+"'"
            + " ,'"+DeptTxt.getText()+"','"+facTxt.getText()+"'"
             + ",?)";
            stmt.execute(Query);
            */
            InputStream is = new FileInputStream(new File(s));
            ps.setString(1, idTxt.getText());
            ps.setString(2, nameTxt.getText());
            ps.setInt(3,classCombo.getSelectedIndex());
            ps.setInt(4,YearCombo.getSelectedIndex());
            ps.setString(5, DeptTxt.getText());
            ps.setString(6, facTxt.getText());
            ps.setBlob(7,is);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"User Added To Database");

            idTxt.setText(null);
            classCombo.setSelectedItem("00");
            YearCombo.setSelectedItem("0000");
            DeptTxt.setText(null);
            facTxt.setText(null);
            imgLabel.setText("");
            

        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
            catch(Exception ex){
               ex.printStackTrace();
           }
    }//GEN-LAST:event_addBtnActionPerformed

    private void AttachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachBtnActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             imgLabel.setIcon(ResizeImage(path));
             s = path;
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }
     
    }//GEN-LAST:event_AttachBtnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void classComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classComboActionPerformed

    private void YearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new display().setVisible(true);
            }
        });
    }
private void close() 
{
    WindowEvent WE = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(WE);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttachBtn;
    private javax.swing.JButton Back;
    private javax.swing.JTextField DeptTxt;
    private javax.swing.JComboBox YearCombo;
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox classCombo;
    private javax.swing.JTextField facTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel main;
    private javax.swing.JTextField nameTxt;
    // End of variables declaration//GEN-END:variables

    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(imgLabel.getWidth(), imgLabel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
}
