/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barc;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.text.*;
import java.awt.print.*;
/**
 *
 * @author Moataz
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
public class NormalSearch extends javax.swing.JFrame {

    
    //private HashMap usersMap ;

    
    public NormalSearch() {
        initComponents();
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        studentCombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Barcode to search :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 220, 30));

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 120, 40));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 80, 30));
        getContentPane().add(imgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 270, 160));

        studentCombo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        studentCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        studentCombo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                studentComboAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        studentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentComboActionPerformed(evt);
            }
        });
        getContentPane().add(studentCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 190, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 120, 40));

        orderTable.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "code", "name", "class", "dept", "date", "faculty"
            }
        ));
        orderTable.setRowHeight(30);
        jScrollPane1.setViewportView(orderTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 1170, 460));

        jButton2.setText("print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        orderTable.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 18));
        ((DefaultTableCellRenderer) orderTable.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment((int) JLabel.CENTER_ALIGNMENT);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        orderTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        for (int x = 0; x < orderTable.getColumnCount(); x++) {
            orderTable.getColumnModel().getColumn(x).setCellRenderer(centerRenderer);
        }
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        int sellPanlerowCount = model.getRowCount();
        for (int i = 0; i < sellPanlerowCount; i++) {
            model.removeRow(0);
        }

                    try {
                Class.forName("com.mysql.jdbc.Driver");

                Connection c = DriverManager.getConnection("jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8", "root", "");
                String s = "select name from  student where name='"+studentCombo.getSelectedItem()+"'";

                Statement st = c.createStatement();
                ResultSet rs = st.executeQuery(s);
                String stu_name="";
                while(rs.next()){
                    stu_name=rs.getString(1);
                }
                
                String s2="select * from student "
                        + " where studentID='"+idTxt.getText()+"'";
            Statement st1 = c.createStatement();
            ResultSet rs1 = st1.executeQuery(s2);
            String code="";
            String date="";
            String name="";
            String dept="";
            String faculty="";
            int class_no=0;
            
            while(rs1.next()){
                code=rs1.getString(1);
                date=rs1.getString(4);
                name=rs1.getString(2);
                class_no=rs1.getInt(3);
                dept=rs1.getString(5);
                faculty=rs1.getString(6);
                model.addRow(new Object[]{ code,name,class_no,dept,date,faculty});

            }

            }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
       setVisible(false);
        new start().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void studentComboAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_studentComboAncestorAdded
 try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8", "root", "");
            String s = "select name from student";
            Statement st = c.createStatement();

            ResultSet rs = st.executeQuery(s);
            String Name="";
            while(rs.next()){
                Name=rs.getString(1);
                studentCombo.addItem(Name);
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_studentComboAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        orderTable.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 18));
        ((DefaultTableCellRenderer) orderTable.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment((int) JLabel.CENTER_ALIGNMENT);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        orderTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        for (int x = 0; x < orderTable.getColumnCount(); x++) {
            orderTable.getColumnModel().getColumn(x).setCellRenderer(centerRenderer);
        }
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        int sellPanlerowCount = model.getRowCount();
        for (int i = 0; i < sellPanlerowCount; i++) {
            model.removeRow(0);
        }
        
         if(studentCombo.getSelectedItem().toString().equals("All")){
            try {
                Class.forName("com.mysql.jdbc.Driver");

            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8", "root", "");
            
            
            String s2="select * from student";
            Statement st1 = c.createStatement();
            ResultSet rs1 = st1.executeQuery(s2);
            String code="";
            String date="";
            String name="";
            String dept="";
            String faculty="";
            int class_no=0;
            
            while(rs1.next()){
                code=rs1.getString(1);
                date=rs1.getString(4);
                name=rs1.getString(2);
                class_no=rs1.getInt(3);
                dept=rs1.getString(5);
                faculty=rs1.getString(6);
                model.addRow(new Object[]{ code,name,class_no,dept,date,faculty});

            }

            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
         }
            else{
        try {
            Class.forName("com.mysql.jdbc.Driver");

            Connection c = DriverManager.getConnection("jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8", "root", "");
            String s = "select name from  student where name='"+studentCombo.getSelectedItem()+"'";

            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery(s);
            String stu_name="";
            while(rs.next()){
                stu_name=rs.getString(1);
            }
            /*String s1 = "select * from  purchase_orders "
                    + "where supplier_id='"+supp_id+"' and reminder > 0";
            
            */
            
            String s2="select * from student where name='"+stu_name+"'";
            Statement st1 = c.createStatement();
            ResultSet rs1 = st1.executeQuery(s2);
            String code="";
            String date="";
            String name="";
            String dept="";
            String faculty="";
            int class_no=0;
            
            while(rs1.next()){
                code=rs1.getString(1);
                date=rs1.getString(4);
                name=rs1.getString(2);
                class_no=rs1.getInt(3);
                dept=rs1.getString(5);
                faculty=rs1.getString(6);
                model.addRow(new Object[]{ code,name,class_no,dept,date,faculty});

            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.print(e);
        }
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String str=" كلية الحاسات و المعلومات";
        MessageFormat header = new MessageFormat("طلاب الحاسبات و المعلومات"+"\r\n"+str);
        MessageFormat footer = new MessageFormat("page{0,number,integer}");
        
    
        try{
       
       orderTable.print(JTable.PrintMode.FIT_WIDTH,header,footer);
       
       
       }
      catch(java.awt.print.PrinterException e){
          
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void studentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NormalSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NormalSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NormalSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NormalSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NormalSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel main;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox studentCombo;
    // End of variables declaration//GEN-END:variables
}
