/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barc;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Moataz
 */
public class Search extends javax.swing.JFrame {

    final void FillList(){
        try{
        String url="jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8" ;
        String username="root";
        String password="";
        Connection con = DriverManager.getConnection(url,username,password);
        Statement stmt = con.createStatement();
        String Query="SELECT * FROM student";
        ResultSet rs = stmt.executeQuery(Query);
        
        DefaultListModel DLM = new DefaultListModel() ;         // de class btro7 3la el list fe el GUI w tshof el default bta3o ya3ni el data btt3rd
                                                                 // default ezay .
                
        
        while(rs.next()) {                // hold ctrl 
            
            DLM.addElement(rs.getString(2));       // dah bydef bel object DLM fe el list 3an tare2 addElement
            
        }
        
        studentList.setModel(DLM);    // el DML dah be hold kol el data elly gaya mn el database fa hawdeha fe List1        // hold ctrl
    }
         catch (SQLException ex)
       {
           JOptionPane.showMessageDialog(null, ex.toString());
    
    
    //private HashMap usersMap ;
       }
    }
    public Search() {
    
        initComponents();
         FillList();     // ana hena 3ashan a5li el code ye run lazem a7ot el function hena fe el class el asaseya
        for (int i = 1900; i < 2050; i++) {
            yearbox.addItem(i);
        } 
        //initUsers();
        
       // idField.requestFocus(); 
        /*
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowActivated(WindowEvent e) {

                nameField.requestFocus();
            }
          
             
        });
        */
        /*
        idField.addKeyListener(new KeyAdapter() {

            @Override
            public void keyTyped(KeyEvent e) {

               // JOptionPane.showMessageDialog(null, idField.getText());
               
                String id = idField.getText() ;
                
                String userName = (String) usersMap.get(id) ;
                
                if(userName != null)
                    
                    nameField.setText(userName);
                
                else
                    
                    nameField.setText(null);
            }
             
        }) ;
        */
               

    }
/*
    private void initUsers()
    {
       usersMap = new HashMap() ;
       
       usersMap.put("123", "Moataz") ;
       
       usersMap.put("345", "Soso") ;
    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        imgLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JList();
        DeleteBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yearbox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        deptTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        facTxt = new javax.swing.JTextField();
        classBox = new javax.swing.JComboBox();
        clearBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Barcode to search :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 220, 30));
        getContentPane().add(imgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 270, 190));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("List of Student");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

        studentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                studentListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(studentList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 390));

        DeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p img/1462225296_user-delete.png"))); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 120, 50));

        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p img/1462227000_user-id.png"))); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 110, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 300, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Class:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Year :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        yearbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select Year" }));
        yearbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearboxActionPerformed(evt);
            }
        });
        getContentPane().add(yearbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));
        getContentPane().add(deptTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 290, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Faculty :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));
        getContentPane().add(facTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 290, 30));

        classBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(classBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 80, -1));

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 120, 50));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 80, 30));

        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barc/pattern-textures_00245516.jpg"))); // NOI18N
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_studentListValueChanged

        //************* el event dah wazefto en kol ma ados 3la ay 7aga mn el data elly fe el list ye3ml 7aga elly haktbha hena b2a ****************


        //************* el event dah wazefto en kol ma ados 3la ay 7aga mn el data elly fe el list ye3ml 7aga elly haktbha hena b2a ****************

        try{
            String url="jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8" ;
            String username="root";
            String password="";

            Connection con = DriverManager.getConnection(url,username,password);
            Statement stmt = con.createStatement();
            String Query="SELECT * FROM student WHERE name = '"+studentList.getSelectedValue()+"'";
            //String Query="SELECT * FROM student WHERE studentID = '"+idTxt.getText()+"'";
            ResultSet rs = stmt.executeQuery(Query);

            if(rs.next()) {                    // ana hena 3ayz lama yela2i data ye set text fe elly haktebo hena

                idTxt.setText(rs.getString(1));
                nameTxt.setText(rs.getString(2));
                classBox.setSelectedItem(rs.getString(3));
                yearbox.setSelectedItem(rs.getInt(4));
                deptTxt.setText(rs.getString(5));
                facTxt.setText(rs.getString(6));
            
            //if(rs.next()){
                byte[] img = rs.getBytes("image");
                ImageIcon image = new ImageIcon(img);
                Image im= image.getImage();
                Image myImg = im.getScaledInstance(imgLabel.getWidth(),imgLabel.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newImage= new ImageIcon(myImg);
                imgLabel.setIcon(newImage);
            //}
            }
            else{
            JOptionPane.showMessageDialog(null,"Student Not Found"); 
             }
            
            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_studentListValueChanged

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
try{
        String url="jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8" ;
        String username="root";
        String password="";
       
        Connection con = DriverManager.getConnection(url,username,password);
        Statement stmt = con.createStatement();
        String Query="DELETE FROM student WHERE name='"+studentList.getSelectedValue()+"'" ;
        stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"User Data is DELETED");
        
        FillList();
 }
           
    
         catch (SQLException ex)
       {
           JOptionPane.showMessageDialog(null, ex.toString());
       } 
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
try{
        String url="jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8" ;
        String username="root";
        String password="";
       
        Connection con = DriverManager.getConnection(url,username,password);
        Statement stmt = con.createStatement();
        String Query="UPDATE student SET studentID='"+idTxt.getText()+"',name='"+nameTxt.getText()+"' "
                + ",class='"+classBox.getSelectedItem()+"',year='"+yearbox.getSelectedItem()+"'"
                + " ,department='"+deptTxt.getText()+"',faculty='"+facTxt.getText()+"' "
                + " ,image='"+imgLabel.getText()+"', "
                +"'WHERE NAME='"+studentList.getSelectedValue()+"'" ;
        stmt.execute(Query);
        JOptionPane.showMessageDialog(null,"Your Data Updated");
        
        FillList();  //************************************* bashof el data elly mawgoda w agebha tany  //
               
        }
           
    
         catch (SQLException ex)
       {
           JOptionPane.showMessageDialog(null, ex.toString());
       } 
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
                idTxt.setText(null);
                nameTxt.setText(null);
                classBox.setSelectedItem("00");
                yearbox.setSelectedItem("0000");
                deptTxt.setText(null);
                facTxt.setText(null);        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
      try{
            String url="jdbc:mysql://localhost/barcode?useUnicode=true&characterEncoding=UTF-8" ;
            String username="root";
            String password="";

            Connection con = DriverManager.getConnection(url,username,password);
            Statement stmt = con.createStatement();
            //String Query="SELECT * FROM student WHERE name = '"+studentList.getSelectedValue()+"'";
            String Query="SELECT * FROM student WHERE studentID = '"+idTxt.getText()+"'";
            ResultSet rs = stmt.executeQuery(Query);

            if(rs.next()) {                    // ana hena 3ayz lama yela2i data ye set text fe elly haktebo hena

                //idTxt.setText(rs.getString(1));
                nameTxt.setText(rs.getString(2));
                classBox.setSelectedItem(rs.getString(3));
                yearbox.setSelectedItem(rs.getInt(4));
                deptTxt.setText(rs.getString(5));
                facTxt.setText(rs.getString(6));
            
            //if(rs.next()){
                byte[] img = rs.getBytes("image");
                ImageIcon image = new ImageIcon(img);
                Image im= image.getImage();
                Image myImg = im.getScaledInstance(imgLabel.getWidth(),imgLabel.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon newImage= new ImageIcon(myImg);
                imgLabel.setIcon(newImage);
            //}
            }
            else{
            JOptionPane.showMessageDialog(null,"Student Not Found"); 
             }
            
            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void yearboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }
private void close() 
{
    WindowEvent WE = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(WE);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JComboBox classBox;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField deptTxt;
    private javax.swing.JTextField facTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel main;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JList studentList;
    private javax.swing.JComboBox yearbox;
    // End of variables declaration//GEN-END:variables
}
