create table emp
(
ID number(3) not null,
ename varchar(10) not null,
job varchar(10) not null,
dno number(2) not null,
salary number(5) not null,
comm number(3)
);
ALTER TABLE EMP ADD CONSTRAINT PK_EMP PRIMARY KEY (ID);

insert into emp values(100,'AMR','SALESMAN',10,300,50);
insert into emp values(101,'SAMY','ENGINEER',20,400,NULL);
insert into emp values(102,'ALI','MANAGER',10,400,100);
insert into emp values(103,'AMANY','SALESMAN',30,300,NULL);
insert into emp values(104,'FADY','ENGINEER',40,600,NULL);
insert into emp values(105,'HANY','TSUPPORT',30,550,50);


CREATE TABLE DEPT
(
DNO NUMBER(2) NOT NULL,
DNAME VARCHAR2(20) NOT NULL,
LOC VARCHAR2(10)
);
ALTER TABLE DEPT ADD CONSTRAINT PK_DEPT PRIMARY KEY(DNO);
ALTER TABLE EMP ADD CONSTRAINT FK_EMP FOREIGN KEY(DNO) REFERENCES DEPT(DNO);

insert into DEPT values(10,'MARKETING','GIZA');
insert into DEPT values(20,'SUPPORT','CAIRO');
insert into DEPT values(30,'MANAGEMENT','ASWAN');
insert into DEPT values(40,'PRODUCTION','ALEX');
insert into DEPT values(50,'IT','CAIRO');

/*QUESTIONS*/
SELECT MAX(SALARY) FROM EMP WHERE DNO IN(SELECT DNO FROM DEPT WHERE LOC IN('GIZA','ALEX'));
SELECT ENAME , DNAME FROM EMP NATURAL JOIN DEPT;
SELECT 10+50*2+6*3-1 FROM DUAL;
SELECT ENAME , ID FROM EMP WHERE ENAME LIKE '_M%';
SELECT LOWER(ENAME) , UPPER(ENAME) FROM EMP WHERE ID IN(100,103);
DELETE FROM EMP WHERE JOB ='SALESMAN' OR SALARY>400;
SELECT ENAME , SALARY+COMM"TOTAL SALARY" FROM EMP WHERE DNO = 30;
INSERT INTO EMP(ID,ENAME,JOB,DNO,SALARY) VALUES(110,'RAMY','TEACHER',60,4500);
SELECT ENAME , SALARY FROM EMP WHERE COMM IS NULL UNION SELECT ENAME , SALARY FROM EMP WHERE SALARY > 400;
SELECT ENAME , DNAME FROM EMP RIGHT OUTER JOIN DEPT ON(EMP.DNO=DEPT.DNO);